# encoding: ascii-8bit

# Self-contained prefix install of COSMOS and the Qt 6 bindings.
#
#   rake install_prefix                                  # -> /local/opt
#   rake install_prefix PREFIX=/opt/cosmos
#   rake install_prefix PREFIX=/local/opt QTBINDINGS=~/src/qtbindings
#
# Produces an FHS-style tree that does not depend on this checkout:
#
#   <prefix>/bin      wrappers that set RUBYLIB/GEM_PATH, plus cosmos_env.sh
#   <prefix>/libexec  the real bin/ scripts the wrappers exec
#   <prefix>/lib      cosmos.rb, cosmos/, and the Qt 6 bindings (qt6.rb, qt6.so)
#   <prefix>/gems     vendored gem dependencies (a GEM_PATH root)
#   <prefix>/data, demo/, install/, config/
#
# Cosmos::PATH is derived two levels up from lib/cosmos/top_level.rb, so with
# lib/ at <prefix>/lib it resolves to <prefix> -- which is why data/, demo/
# and install/ have to sit directly under the prefix for `cosmos demo` and the
# tools' data files to be found.

require 'fileutils'
require 'rbconfig'

PREFIX_DEFAULT = '/local/opt'
# Group-readable so others can run the install; only the owner can update it.
INSTALL_DIR_MODE = 0o755

def prefix_paths
  prefix = File.expand_path(ENV['PREFIX'] || PREFIX_DEFAULT)
  { prefix: prefix,
    bin: File.join(prefix, 'bin'),
    libexec: File.join(prefix, 'libexec'),
    lib: File.join(prefix, 'lib'),
    gems: File.join(prefix, 'gems') }
end

# The gems are taken from `bundle install --path vendor/bundle`, whose layout
# (ruby/<abi>/{gems,specifications,extensions}) is already a valid GEM_PATH
# root, so the wrappers can point plain RubyGems at it with no bundler.
def gem_abi
  RbConfig::CONFIG['ruby_version']
end

def qtbindings_root
  root = ENV['QTBINDINGS'] || File.expand_path('~/src/qtbindings')
  File.expand_path(root)
end

def install_tree(src, dest)
  FileUtils.mkdir_p(dest, mode: INSTALL_DIR_MODE)
  FileUtils.cp_r(File.join(src, '.'), dest)
end

desc "Install COSMOS and the Qt 6 bindings into PREFIX (default #{PREFIX_DEFAULT})"
task :install_prefix do
  paths = prefix_paths
  prefix = paths[:prefix]
  qt = qtbindings_root

  # --- preflight: fail before writing anything ---------------------------
  qt_ext = Dir.glob(File.join(qt, 'ext/qt6/qt6.{so,bundle}')).first
  unless qt_ext
    abort "Qt 6 bindings are not built at #{qt}/ext/qt6.\n" \
          "Build them first (cd #{qt}/ext/qt6 && ruby extconf.rb && make), " \
          'or point QTBINDINGS= at another checkout.'
  end
  unless Dir.exist?(File.join(__dir__, '..', 'vendor/bundle/ruby', gem_abi))
    abort "No vendored gems at vendor/bundle/ruby/#{gem_abi}.\n" \
          'Run: bundle config set --local path vendor/bundle && bundle install'
  end
  if Dir.glob(File.join(__dir__, '..', 'lib/cosmos/ext/*.{so,bundle}')).empty?
    abort "COSMOS C extensions are not built.\nRun: bundle exec rake build"
  end

  root = File.expand_path('..', __dir__)
  puts "Installing COSMOS to #{prefix} (ruby #{gem_abi}, qtbindings #{qt})"
  FileUtils.mkdir_p(prefix, mode: INSTALL_DIR_MODE)

  # --- COSMOS library and the data the tools read at runtime -------------
  FileUtils.rm_rf(paths[:lib])
  install_tree(File.join(root, 'lib'), paths[:lib])
  %w[data demo install config].each do |dir|
    src = File.join(root, dir)
    next unless Dir.exist?(src)
    dest = File.join(prefix, dir)
    FileUtils.rm_rf(dest)
    install_tree(src, dest)
  end

  # --- Qt 6 bindings, flattened next to cosmos.rb ------------------------
  # qt6.rb falls back to `require 'qt6.so'` from the load path, so the
  # extension sits beside it rather than in an ext/ subtree.
  install_tree(File.join(qt, 'lib'), paths[:lib])
  FileUtils.cp(qt_ext, File.join(paths[:lib], File.basename(qt_ext)))

  # --- gem dependencies ---------------------------------------------------
  FileUtils.rm_rf(paths[:gems])
  install_tree(File.join(root, 'vendor/bundle'), paths[:gems])

  # --- executables --------------------------------------------------------
  FileUtils.rm_rf(paths[:libexec])
  FileUtils.mkdir_p(paths[:libexec], mode: INSTALL_DIR_MODE)
  FileUtils.mkdir_p(paths[:bin], mode: INSTALL_DIR_MODE)

  gem_path = File.join(paths[:gems], 'ruby', gem_abi)
  executables = Dir.glob(File.join(root, 'bin/*')).reject do |f|
    File.directory?(f) || f.end_with?('.dll')
  end

  executables.each do |script|
    name = File.basename(script)
    FileUtils.cp(script, File.join(paths[:libexec], name))
    FileUtils.chmod(0o755, File.join(paths[:libexec], name))

    wrapper = File.join(paths[:bin], name)
    File.open(wrapper, 'w') do |f|
      f.puts '#!/bin/bash'
      f.puts "# COSMOS #{name} -- generated by rake install_prefix"
      f.puts "PREFIX=#{prefix}"
      f.puts 'export GEM_PATH="$PREFIX/gems/ruby/' + gem_abi + '${GEM_PATH:+:$GEM_PATH}"'
      f.puts 'export RUBYLIB="$PREFIX/lib${RUBYLIB:+:$RUBYLIB}"'
      f.puts "exec ruby \"$PREFIX/libexec/#{name}\" \"$@\""
    end
    FileUtils.chmod(0o755, wrapper)
  end

  # Sourceable environment, for running a project's own tools
  # (demo/Launcher and friends) outside these wrappers.
  env_script = File.join(paths[:bin], 'cosmos_env.sh')
  File.open(env_script, 'w') do |f|
    f.puts '# Source this to put COSMOS on your environment:'
    f.puts "#   source #{env_script}"
    f.puts "PREFIX=#{prefix}"
    f.puts 'export GEM_PATH="$PREFIX/gems/ruby/' + gem_abi + '${GEM_PATH:+:$GEM_PATH}"'
    f.puts 'export RUBYLIB="$PREFIX/lib${RUBYLIB:+:$RUBYLIB}"'
    f.puts 'export PATH="$PREFIX/bin:$PATH"'
    f.puts '# The Qt 6 bindings are installed into $PREFIX/lib, so they are'
    f.puts '# already on RUBYLIB and COSMOS_QT6_LIB is not needed.'
    f.puts 'echo "COSMOS environment ready ($PREFIX)"'
  end
  FileUtils.chmod(0o644, env_script)

  # --- permissions: group-readable, owner-writable ------------------------
  # Set modes explicitly: chmod_R's `X` does not pick up shared objects, so
  # a copied qt6.so would land group-unreadable/unexecutable.
  Dir.glob(File.join(prefix, '**', '*'), File::FNM_DOTMATCH).each do |path|
    next if File.symlink?(path)
    if File.directory?(path)
      FileUtils.chmod(0o755, path)
    elsif path.end_with?('.so', '.bundle') || File.executable?(path)
      FileUtils.chmod(0o755, path)
    else
      FileUtils.chmod(0o644, path)
    end
  end
  FileUtils.chmod(0o755, prefix)

  puts
  puts "Installed to #{prefix}"
  puts "  #{executables.length} executables in #{paths[:bin]}"
  puts "  library          #{paths[:lib]}"
  puts "  gems (GEM_PATH)  #{gem_path}"
  puts
  puts 'Try it:'
  puts "  #{File.join(paths[:bin], 'cosmos')} help"
  puts "  source #{env_script}"
end

desc 'Remove a prefix install (PREFIX=, default ' + PREFIX_DEFAULT + ')'
task :uninstall_prefix do
  paths = prefix_paths
  # Only remove what install_prefix creates, never the prefix itself -- it may
  # be a shared directory with other things in it.
  %i[bin libexec lib gems].each { |k| FileUtils.rm_rf(paths[k]) }
  %w[data demo install config].each do |dir|
    FileUtils.rm_rf(File.join(paths[:prefix], dir))
  end
  puts "Removed COSMOS from #{paths[:prefix]}"
end
